clients.typescript.build:
  stage: build
  dependencies: []
  rules:
    - changes:
        - clients/typescript/**/*
  image: node:$NODE_VERSION
  script:
    - pushd clients/typescript/
    - npm install
    - npm test
    - npm run build
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - clients/typescript/node_modules/
      - clients/typescript/dist/

clients.typescript.check:
  stage: test
  dependencies:
    - clients.typescript.build
  rules:
    - changes:
        - clients/typescript/**/*
  image: node:$NODE_VERSION
  script:
    - pushd clients/typescript/
    - npm run check-full

clients.typescript.release:
  image: node:22
  stage: release
  variables:
    CI: "true"
  before_script:
    - git remote set-url origin "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"
    - npm install
  script:
    - npx semantic-release
  only:
    - master

