name: Build and Publish Docker Images

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: api
            platform: linux/amd64
            runner: blacksmith-4vcpu-ubuntu-2204
          - image: api
            platform: linux/arm64
            runner: blacksmith-4vcpu-ubuntu-2204-arm	
          - image: frontend
            platform: linux/amd64
            runner: blacksmith-4vcpu-ubuntu-2204
          - image: frontend
            platform: linux/arm64
            runner: blacksmith-4vcpu-ubuntu-2204-arm
          - image: output-worker
            platform: linux/amd64
            runner: blacksmith-4vcpu-ubuntu-2204
          - image: output-worker
            platform: linux/arm64
            runner: blacksmith-4vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image }} image
        uses: useblacksmith/build-push-action@v1
        with:
          context: .
          file: ${{ matrix.image }}/Dockerfile
          platforms: ${{ matrix.platform }}
          # cache-from: |
          #   type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}:build-cache
          #   type=gha
          # cache-to: |
          #   type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}:build-cache,mode=max
          #   type=gha,mode=max
          push: true
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            ${{ matrix.image == 'api' && 'FEATURES=reqwest-rustls-tls-webpki-roots,application-secret-compatibility' || '' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}